version: '3.10'

services:
  fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app
    command: uvicorn app:app --reload --host=0.0.0.0 --port=4000
